project_id = "kspzfifdwfpirgqstzhz"

[functions.register-tenant]
verify_jwt = false

[functions.admin-create-org-user]
verify_jwt = true

[functions.send-verification-code]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false