-- Seed some sample proposal templates
-- This script adds real templates to the database for testing

-- Insert sample proposal templates
INSERT INTO documents (
  id,
  title,
  description,
  file_name,
  file_path,
  mime_type,
  file_size,
  category,
  template_category,
  is_template,
  status,
  org_id,
  created_by,
  created_at,
  updated_at
) VALUES 
  (
    gen_random_uuid(),
    'Education Initiative Proposal Template',
    'A comprehensive template for education-focused project proposals including objectives, methodology, and budget sections.',
    'education-proposal-template.docx',
    'templates/education-proposal-template.docx',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    45000,
    'templates',
    'proposal',
    true,
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM profiles WHERE org_id = (SELECT id FROM organizations LIMIT 1) LIMIT 1),
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Health Program Proposal Template',
    'Template for health and medical program proposals with detailed sections for impact assessment and sustainability.',
    'health-proposal-template.docx',
    'templates/health-proposal-template.docx',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    52000,
    'templates',
    'proposal',
    true,
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM profiles WHERE org_id = (SELECT id FROM organizations LIMIT 1) LIMIT 1),
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Community Development Proposal Template',
    'A structured template for community development projects including stakeholder analysis and risk assessment.',
    'community-proposal-template.docx',
    'templates/community-proposal-template.docx',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    48000,
    'templates',
    'proposal',
    true,
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM profiles WHERE org_id = (SELECT id FROM organizations LIMIT 1) LIMIT 1),
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Environmental Project Proposal Template',
    'Template for environmental conservation and sustainability projects with focus on impact measurement.',
    'environment-proposal-template.docx',
    'templates/environment-proposal-template.docx',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    41000,
    'templates',
    'proposal',
    true,
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM profiles WHERE org_id = (SELECT id FROM organizations LIMIT 1) LIMIT 1),
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Grant Application Template',
    'General purpose grant application template suitable for various funding opportunities.',
    'grant-application-template.docx',
    'templates/grant-application-template.docx',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    38000,
    'templates',
    'proposal',
    true,
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM profiles WHERE org_id = (SELECT id FROM organizations LIMIT 1) LIMIT 1),
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Project Report Template',
    'Standard template for project progress and final reports with sections for achievements and challenges.',
    'project-report-template.docx',
    'templates/project-report-template.docx',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    35000,
    'templates',
    'report',
    true,
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM profiles WHERE org_id = (SELECT id FROM organizations LIMIT 1) LIMIT 1),
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING;
