-- Insert development user profiles (they need to sign up first, but we'll prepare the org data)
-- These will be linked when the development users sign up with Supabase Auth

-- Note: The actual user IDs will be generated by Supabase Auth when users sign up
-- For now, we just ensure the organizations and contacts are ready