-- Add sample proposals data for testing
INSERT INTO public.proposals (
  org_id,
  name,
  title,
  due_date,
  reviewer,
  team,
  status,
  budget_currency,
  budget_amount,
  overview_fields,
  narrative_fields,
  logframe_fields,
  attachments,
  submission_status,
  created_by
) VALUES 
-- Proposals In Progress
(
  (SELECT id FROM organizations LIMIT 1),
  'Climate Change Mitigation Initiative',
  'Climate Change Mitigation Initiative',
  '2025-01-15',
  'Winifred John',
  '[{"label": "WJ", "bg": "bg-purple-100"}, {"label": "SO", "bg": "bg-blue-100"}, {"label": "CI", "bg": "bg-green-100"}]'::jsonb,
  'in_progress',
  'USD',
  250000,
  '[{"type": "text", "label": "Project Title", "value": "Climate Change Mitigation Initiative"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "A comprehensive initiative to address climate change through sustainable practices and renewable energy solutions."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'draft',
  (SELECT id FROM profiles LIMIT 1)
),
(
  (SELECT id FROM organizations LIMIT 1),
  'Education Access Program',
  'Education Access Program',
  '2025-02-20',
  'Somachi Okafor',
  '[{"label": "SO", "bg": "bg-blue-100"}, {"label": "RN", "bg": "bg-yellow-100"}]'::jsonb,
  'in_progress',
  'USD',
  180000,
  '[{"type": "text", "label": "Project Title", "value": "Education Access Program"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "Improving access to quality education for underserved communities through technology and infrastructure development."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'draft',
  (SELECT id FROM profiles LIMIT 1)
),
(
  (SELECT id FROM organizations LIMIT 1),
  'Community Health Initiative',
  'Community Health Initiative',
  '2025-01-30',
  'Chioma Ike',
  '[{"label": "CI", "bg": "bg-green-100"}, {"label": "AY", "bg": "bg-pink-100"}]'::jsonb,
  'in_progress',
  'USD',
  320000,
  '[{"type": "text", "label": "Project Title", "value": "Community Health Initiative"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "Strengthening healthcare systems and improving health outcomes in rural communities."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'draft',
  (SELECT id FROM profiles LIMIT 1)
),

-- Pending Reviews (Under Review)
(
  (SELECT id FROM organizations LIMIT 1),
  'Women Empowerment Project',
  'Women Empowerment Project',
  '2025-03-15',
  'Richard Nwamadi',
  '[{"label": "RN", "bg": "bg-yellow-100"}, {"label": "WJ", "bg": "bg-purple-100"}]'::jsonb,
  'under_review',
  'USD',
  150000,
  '[{"type": "text", "label": "Project Title", "value": "Women Empowerment Project"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "Empowering women through skills training, micro-finance, and leadership development programs."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'submitted',
  (SELECT id FROM profiles LIMIT 1)
),
(
  (SELECT id FROM organizations LIMIT 1),
  'Youth Leadership Development',
  'Youth Leadership Development',
  '2025-02-28',
  'Amina Yusuf',
  '[{"label": "AY", "bg": "bg-pink-100"}, {"label": "CI", "bg": "bg-green-100"}]'::jsonb,
  'under_review',
  'USD',
  95000,
  '[{"type": "text", "label": "Project Title", "value": "Youth Leadership Development"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "Building leadership capacity among young people through mentorship and training programs."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'submitted',
  (SELECT id FROM profiles LIMIT 1)
),

-- Archived Proposals (Approved)
(
  (SELECT id FROM organizations LIMIT 1),
  'Clean Water Access Initiative',
  'Clean Water Access Initiative',
  '2024-12-15',
  'Winifred John',
  '[{"label": "WJ", "bg": "bg-purple-100"}, {"label": "SO", "bg": "bg-blue-100"}]'::jsonb,
  'approved',
  'USD',
  275000,
  '[{"type": "text", "label": "Project Title", "value": "Clean Water Access Initiative"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "Providing clean and safe drinking water to remote communities through sustainable water systems."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'approved',
  (SELECT id FROM profiles LIMIT 1)
),
(
  (SELECT id FROM organizations LIMIT 1),
  'Digital Literacy Program',
  'Digital Literacy Program',
  '2024-11-30',
  'Somachi Okafor',
  '[{"label": "SO", "bg": "bg-blue-100"}, {"label": "RN", "bg": "bg-yellow-100"}]'::jsonb,
  'approved',
  'USD',
  120000,
  '[{"type": "text", "label": "Project Title", "value": "Digital Literacy Program"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "Teaching digital skills to improve employment opportunities and access to information."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'approved',
  (SELECT id FROM profiles LIMIT 1)
),

-- Archived Proposals (Rejected)
(
  (SELECT id FROM organizations LIMIT 1),
  'Renewable Energy Project',
  'Renewable Energy Project',
  '2024-12-01',
  'Chioma Ike',
  '[{"label": "CI", "bg": "bg-green-100"}]'::jsonb,
  'rejected',
  'USD',
  450000,
  '[{"type": "text", "label": "Project Title", "value": "Renewable Energy Project"}]'::jsonb,
  '[{"type": "textarea", "label": "Project Description", "value": "Installing solar panels and wind turbines for sustainable energy generation."}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'rejected',
  (SELECT id FROM profiles LIMIT 1)
);