// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aovudmxxfbfnydrdowhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdnVkbXh4ZmJmbnlkcmRvd2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDkxMzQsImV4cCI6MjA2OTM4NTEzNH0.aN8DLc8RqDHrwTE3YIUclGCHAfuzPM7ta2Ou41zP59w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});